#!/bin/bash

export GIT_EDITOR=vim
if [ -n "$ZSH_VERSION" ]; then
    # assume Zsh
    # completition build in 
elif [ -n "$BASH_VERSION" ]; then
    # assume Bash
    if [ -f  /usr/share/git/completion/git-completion.bash ] ; then
       source /usr/share/git/completion/git-completion.bash
    fi
fi
