if ! [ -f  ~/.allshesllsrc.base ] ; then echo "No such file: ~/.allshesllsrc.base" ; fi
source ~/.allshesllsrc.base

source ~/.zprezto/init.zsh

. /usr/share/stderred/stderred.sh

# TODO: Rename
source_rc .env/bash_functions
source_rc .env/dirs
source_rc .env/base 
source_rc .env/vim
source_rc .env/git
source_rc .env/tmux.common
source_rc .env/java

if tty > /dev/null; then
	source_rc .env/aliases
fi

# generated with  zkbd 
source ~/.zkbd/xterm-256color-:0

# setup key accordingly
[[ -n "${key[Home]}"    ]]  && bindkey  "${key[Home]}"    beginning-of-line
[[ -n "${key[End]}"     ]]  && bindkey  "${key[End]}"     end-of-line
[[ -n "${key[Insert]}"  ]]  && bindkey  "${key[Insert]}"  overwrite-mode
[[ -n "${key[Delete]}"  ]]  && bindkey  "${key[Delete]}"  delete-char
[[ -n "${key[Up]}"      ]]  && bindkey  "${key[Up]}"      up-line-or-history
[[ -n "${key[Down]}"    ]]  && bindkey  "${key[Down]}"    down-line-or-history
[[ -n "${key[Left]}"    ]]  && bindkey  "${key[Left]}"    backward-char
[[ -n "${key[Right]}"   ]]  && bindkey  "${key[Right]}"   forward-char

. /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
. ~/.liquidprompt/liquidprompt


setopt noautomenu
setopt nomenucomplete
#setopt +o menucomplete

# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored _approximate
zstyle ':completion:*' group-name ''
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' verbose true
zstyle :compinstall filename '/home/alpar/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

bindkey "${key[PageUp]}" history-beginning-search-backward
bindkey "${key[PageDown]}" history-beginning-search-forward

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

[[ -f /usr/bin/aws_zsh_completer.sh ]] && source /usr/bin/aws_zsh_completer.sh
[[ -f /opt/google-cloud-sdk/path.zsh.inc ]] && source /opt/google-cloud-sdk/path.zsh.inc
[[ -f /opt/google-cloud-sdk/completion.zsh.inc ]] && source /opt/google-cloud-sdk/completion.zsh.inc

